apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sa-ingress-web-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /sentiment
        backend:
          serviceName: sa-web-app
          servicePort: 80