version: "2.0"

services:
  sa-frontend:
    build: 
      context: ./sa-frontend
    image: aasha/sentiment-analysis-frontend
    ports:
    - "80:80"

  sa-webapp:
    build: 
      context: ./sa-webapp
    image: aasha/sa-webapp
    ports:
    - "8080:8080"
    environment:
    - SA_LOGIC_API_URL=http://sa-logic:5000
    links:
    - sa-logic

  sa-logic:
    build:
      context: ./sa-logic
    image: aasha/sa-logic
    ports:
    - "5050:5000"